# Bar Chart Race, Explained

* Code Source: https://observablehq.com/@d3/bar-chart-race-explained

In [1]:
const fs = require("fs");
const { parse } = require("csv-parse");
const d3 = require("./nodejs/d3.js");

In [3]:
data = []
fs.createReadStream("./data/category-brands.csv")
    .pipe(parse({delimiter: ",", from_line: 2}))
    .on("data", function (row){
        data.push(
            {
                "date": row[0],
                "name": row[1],
                "category": row[2],
                "value": row[3]
            }
        );
    });

Parser {
  _readableState: ReadableState {
    objectMode: true,
    highWaterMark: 16,
    buffer: BufferList { head: null, tail: null, length: 0 },
    length: 0,
    pipes: [],
    flowing: true,
    ended: false,
    endEmitted: false,
    reading: false,
    constructed: true,
    sync: false,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: true,
    errorEmitted: false,
    emitClose: true,
    autoDestroy: true,
    destroyed: false,
    errored: null,
    closed: false,
    closeEmitted: false,
    defaultEncoding: 'utf8',
    awaitDrainWriters: null,
    multiAwaitDrain: false,
    readingMore: false,
    dataEmitted: false,
    decoder: null,
    encoding: null,
    [Symbol(kPaused)]: false
  },
  _events: [Object: null prototype] {
    prefinish: [Function: prefinish],
    unpipe: [Function: onunpipe],
    error: [Function: onerror],
    close: [Function: bound onceWrapper] { listener: [Function: onclose] },
    finish: [Function: bound onceWrapper] { listener: [Function: onfinish] },
    data: [Function (anonymous)]
  },
  _eventsCount: 6,
  _maxListeners: undefined,
  _writableState: WritableState {
    objectMode: false,
    highWaterMark: 16384,
    finalCalled: false,
    needDrain: false,
    ending: false,
    ended: false,
    finished: false,
    destroyed: false,
    decodeStrings: true,
    defaultEncoding: 'utf8',
    length: 0,
    writing: false,
    corked: 0,
    sync: true,
    bufferProcessing: false,
    onwrite: [Function: bound onwrite],
    writecb: null,
    writelen: 0,
    afterWriteTickInfo: null,
    buffered: [],
    bufferedIndex: 0,
    allBuffers: true,
    allNoop: true,
    pendingcb: 0,
    constructed: true,
    prefinished: false,
    errorEmitted: false,
    emitClose: true,
    autoDestroy: true,
    errored: null,
    closed: false,
    closeEmitted: false,
    [Symbol(kOnFinished)]: []
  },
  allowHalfOpen: true,
  api: {
    info: {
      bytes: 0,
      comment_lines: 0,
      empty_lines: 0,
      invalid_field_length: 0,
      lines: 1,
      records: 0
    },
    original_options: { delimiter: ',', from_line: 2 },
    options: {
      delimiter: [Array],
      from_line: 2,
      encoding: 'utf8',
      bom: false,
      cast_function: null,
      cast: undefined,
      cast_date: false,
      cast_first_line_to_header: null,
      columns: false,
      group_columns_by_name: false,
      comment: null,
      escape: <Buffer 22>,
      from: 1,
      ignore_last_delimiters: false,
      info: false,
      max_record_size: 0,
      objname: undefined,
      on_record: undefined,
      quote: <Buffer 22>,
      raw: false,
      record_delimiter: [],
      relax_column_count: false,
      relax_column_count_less: false,
      relax_column_count_more: false,
      relax_quotes: false,
      skip_empty_lines: false,
      skip_records_with_empty_values: false,
      skip_records_with_error: false,
      rtrim: false,
      ltrim: false,
      trim: false,
      to: -1,
      to_line: -1,
      on_skip: [Function (anonymous)]
    },
    state: {
      bomSkipped: false,
      bufBytesStart: 0,
      castField: null,
      commenting: false,
      error: undefined,
      enabled: false,
      escaping: false,
      escapeIsQuote: true,
      expectedRecordLength: undefined,
      field: [ResizeableBuffer],
      firstLineToHeaders: null,
      needMoreDataSize: 1,
      previousBuf: undefined,
      quoting: false,
      stop: false,
      rawBuffer: [ResizeableBuffer],
      record: [],
      recordHasError: false,
      record_length: 0,
      recordDelimiterMaxLength: 0,
      trimChars: [Array],
      wasQuoting: false,
      wasRowDelimiter: false,
      timchars: [Array]
    },
    __needMoreData: [Function: __needMoreData],
    parse: [Function: parse],
    __onRecord: [Function: __onRecord],
    __firstLineToColumns: [Function: __firstLineToColumns],
    __resetRecord: [Function: __resetRecord],
    __onField: [Function: __onField],
    __resetField: [Function: __resetField],
    __push: [Function: __push],
    __cast: [Function: __cast],
    __isCharTrimable: [Function: __isCharTrimable],
    __isFloat: [Function: __isFloat],
    __compareBytes: [Function: __compareBytes],
    __isDelimiter: [Function: __isDelimiter],
    __isRecordDelimiter: [Function: __isRecordDelimiter],
    __isEscape: [Function: __isEscape],
    __isQuote: [Function: __isQuote],
    __autoDiscoverRecordDelimiter: [Function: __autoDiscoverRecordDelimiter],
    __error: [Function: __error],
    __infoDataSet: [Function: __infoDataSet],
    __infoRecord: [Function: __infoRecord],
    __infoField: [Function: __infoField]
  },
  state: {
    bomSkipped: false,
    bufBytesStart: 0,
    castField: null,
    commenting: false,
    error: undefined,
    enabled: false,
    escaping: false,
    escapeIsQuote: true,
    expectedRecordLength: undefined,
    field: ResizeableBuffer {
      size: 20,
      length: 0,
      buf: <Buffer 10 3f c0 d1 26 01 00 00 58 d5 da d1 26 01 00 00 f8 d1 da d1>
    },
    firstLineToHeaders: null,
    needMoreDataSize: 1,
    previousBuf: undefined,
    quoting: false,
    stop: false,
    rawBuffer: ResizeableBuffer {
      size: 100,
      length: 0,
      buf: <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 25 00 00 00 26 01 00 00 48 d1 da d1 26 01 00 00 00 d0 ... 50 more bytes>
    },
    record: [],
    recordHasError: false,
    record_length: 0,
    recordDelimiterMaxLength: 0,
    trimChars: [ 32, 9 ],
    wasQuoting: false,
    wasRowDelimiter: false,
    timchars: [ <Buffer 0d>, <Buffer 0a>, <Buffer 0c>, <Buffer 20>, <Buffer 09> ]
  },
  options: {
    delimiter: [ <Buffer 2c> ],
    from_line: 2,
    encoding: 'utf8',
    bom: false,
    cast_function: null,
    cast: undefined,
    cast_date: false,
    cast_first_line_to_header: null,
    columns: false,
    group_columns_by_name: false,
    comment: null,
    escape: <Buffer 22>,
    from: 1,
    ignore_last_delimiters: false,
    info: false,
    max_record_size: 0,
    objname: undefined,
    on_record: undefined,
    quote: <Buffer 22>,
    raw: false,
    record_delimiter: [],
    relax_column_count: false,
    relax_column_count_less: false,
    relax_column_count_more: false,
    relax_quotes: false,
    skip_empty_lines: false,
    skip_records_with_empty_values: false,
    skip_records_with_error: false,
    rtrim: false,
    ltrim: false,
    trim: false,
    to: -1,
    to_line: -1,
    on_skip: [Function (anonymous)]
  },
  info: {
    bytes: 0,
    comment_lines: 0,
    empty_lines: 0,
    invalid_field_length: 0,
    lines: 1,
    records: 0
  },
  [Symbol(kCapture)]: false,
  [Symbol(kCallback)]: null
}

In [9]:
const duration = 250

In [10]:
data

[
  {
    date: '2000-01-01',
    name: 'Coca-Cola',
    category: 'Beverages',
    value: '72537'
  },
  {
    date: '2000-01-01',
    name: 'Microsoft',
    category: 'Technology',
    value: '70196'
  },
  {
    date: '2000-01-01',
    name: 'IBM',
    category: 'Business Services',
    value: '53183'
  },
  {
    date: '2000-01-01',
    name: 'Intel',
    category: 'Technology',
    value: '39048'
  },
  {
    date: '2000-01-01',
    name: 'Nokia',
    category: 'Technology',
    value: '38528'
  },
  {
    date: '2000-01-01',
    name: 'GE',
    category: 'Diversified',
    value: '38127'
  },
  {
    date: '2000-01-01',
    name: 'Ford',
    category: 'Automotive',
    value: '36368'
  },
  {
    date: '2000-01-01',
    name: 'Disney',
    category: 'Media',
    value: '33553'
  },
  {
    date: '2000-01-01',
    name: "McDonald's",
    category: 'Restaurants',
    value: '27859'
  },
  {
    date: '2000-01-01',
    name: 'AT&T',
    category: 'Telecommunications',
    value: '25548'
  },
  {
    date: '2000-01-01',
    name: 'Marlboro',
    category: 'Tobacco',
    value: '22110'
  },
  {
    date: '2000-01-01',
    name: 'Mercedes-Benz',
    category: 'Automotive',
    value: '21104'
  },
  {
    date: '2000-01-01',
    name: 'HP',
    category: 'Electronics',
    value: '20572'
  },
  {
    date: '2000-01-01',
    name: 'Cisco',
    category: 'Business Services',
    value: '20067'
  },
  {
    date: '2000-01-01',
    name: 'Toyota',
    category: 'Automotive',
    value: '18823'
  },
  {
    date: '2000-01-01',
    name: 'Citi',
    category: 'Financial Services',
    value: '18809'
  },
  {
    date: '2000-01-01',
    name: 'Gillette',
    category: 'FMCG',
    value: '17358'
  },
  {
    date: '2000-01-01',
    name: 'Sony',
    category: 'Electronics',
    value: '16409'
  },
  {
    date: '2000-01-01',
    name: 'American Express',
    category: 'Financial Services',
    value: '16122'
  },
  {
    date: '2000-01-01',
    name: 'Honda',
    category: 'Automotive',
    value: '15244'
  },
  {
    date: '2000-01-01',
    name: 'Compaq',
    category: 'Technology',
    value: '14602'
  },
  {
    date: '2000-01-01',
    name: 'NESCAFÉ',
    category: 'Beverages',
    value: '13680'
  },
  {
    date: '2000-01-01',
    name: 'BMW',
    category: 'Automotive',
    value: '12969'
  },
  {
    date: '2000-01-01',
    name: 'Kodak',
    category: 'Electronics',
    value: '11822'
  },
  {
    date: '2000-01-01',
    name: 'Heinz',
    category: 'FMCG',
    value: '11742'
  },
  {
    date: '2000-01-01',
    name: 'Budweiser',
    category: 'Alcohol',
    value: '10684'
  },
  {
    date: '2000-01-01',
    name: 'Xerox',
    category: 'Business Services',
    value: '9699'
  },
  {
    date: '2000-01-01',
    name: 'Dell',
    category: 'Electronics',
    value: '9476'
  },
  {
    date: '2000-01-01',
    name: 'Gap',
    category: 'Apparel',
    value: '9316'
  },
  {
    date: '2000-01-01',
    name: 'Nike',
    category: 'Sporting Goods',
    value: '8015'
  },
  {
    date: '2000-01-01',
    name: 'Volkswagen',
    category: 'Automotive',
    value: '7834'
  },
  {
    date: '2000-01-01',
    name: 'Ericsson',
    category: 'Electronics',
    value: '7805'
  },
  {
    date: '2000-01-01',
    name: "Kellogg's",
    category: 'FMCG',
    value: '7357'
  },
  {
    date: '2000-01-01',
    name: 'Louis Vuitton',
    category: 'Luxury',
    value: '6887'
  },
  {
    date: '2000-01-01',
    name: 'Pepsi',
    category: 'Beverages',
    value: '6636'
  },
  {
    date: '2000-01-01',
    name: 'Apple',
    category: 'Technology',
    value: '6594'
  },
  { date: '2000-01-01', name: 'MTV', category: 'Media', value: '6411' },
  {
    date: '2000-01-01',
    name: 'Yahoo!',
    category: 'Media',
    value: '6299'
  },
  {
    date: '2000-01-01',
    name: 'SAP',
    category: 'Business Services',
    value: '6135'
  },
  {
    date: '2000-01-01',
    name: 'IKEA',
    category: 'Retail',
    value: '6031'
  },
  {
    date: '2000-01-01',
    name: 'Duracell',
    category: 'FMCG',
    value: '5885'
  },
  {
    date: '2000-01-01',
    name: 'Philips',
    category: 'Electronics',
    value: '5481'
  },
  {
    date: '2000-01-01',
    name: 'Samsung',
    category: 'Technology',
    value: '5223'
  },
  {
    date: '2000-01-01',
    name: 'Gucci',
    category: 'Luxury',
    value: '5149'
  },
  {
    date: '2000-01-01',
    name: 'Kleenex',
    category: 'FMCG',
    value: '5144'
  },
  {
    date: '2000-01-01',
    name: 'Reuters',
    category: 'Media',
    value: '4876'
  },
  { date: '2000-01-01', name: 'AOL', category: 'Media', value: '4531' },
  {
    date: '2000-01-01',
    name: 'Amazon',
    category: 'Technology',
    value: '4528'
  },
  {
    date: '2000-01-01',
    name: 'Motorola',
    category: 'Electronics',
    value: '4445'
  },
  {
    date: '2000-01-01',
    name: 'Colgate',
    category: 'FMCG',
    value: '4417'
  },
  {
    date: '2000-01-01',
    name: 'Wrigley',
    category: 'FMCG',
    value: '4324'
  },
  {
    date: '2000-01-01',
    name: 'Chanel',
    category: 'Luxury',
    value: '4141'
  },
  {
    date: '2000-01-01',
    name: 'adidas',
    category: 'Sporting Goods',
    value: '3791'
  },
  {
    date: '2000-01-01',
    name: 'Panasonic',
    category: 'Electronics',
    value: '3734'
  },
  {
    date: '2000-01-01',
    name: 'Rolex',
    category: 'Luxury',
    value: '3561'
  },
  {
    date: '2000-01-01',
    name: 'Hertz',
    category: 'Automotive',
    value: '3438'
  },
  {
    date: '2000-01-01',
    name: 'Bacardi',
    category: 'Alcohol',
    value: '3187'
  },
  { date: '2000-01-01', name: 'BP', category: 'Energy', value: '3066' },
  {
    date: '2000-01-01',
    name: 'Moët & Chandon',
    category: 'Alcohol',
    value: '2799'
  },
  {
    date: '2000-01-01',
    name: 'Shell',
    category: 'Energy',
    value: '2786'
  },
  {
    date: '2000-01-01',
    name: 'Burger King',
    category: 'Restaurants',
    value: '2701'
  },
  {
    date: '2000-01-01',
    name: 'Smirnoff',
    category: 'Alcohol',
    value: '2443'
  },
  {
    date: '2000-01-01',
    name: 'Barbie',
    category: 'Toys & Games',
    value: '2315'
  },
  {
    date: '2000-01-01',
    name: 'Heineken',
    category: 'Alcohol',
    value: '2218'
  },
  {
    date: '2000-01-01',
    name: 'Wall Street Journal',
    category: 'Media',
    value: '2184'
  },
  {
    date: '2000-01-01',
    name: 'Ralph Lauren',
    category: 'Apparel',
    value: '1834'
  },
  {
    date: '2000-01-01',
    name: 'Johnnie Walker',
    category: 'Alcohol',
    value: '1541'
  },
  {
    date: '2000-01-01',
    name: 'Hilton',
    category: 'Hospitality',
    value: '1483'
  },
  {
    date: '2000-01-01',
    name: "Jack Daniel's",
    category: 'Alcohol',
    value: '1480'
  },
  {
    date: '2000-01-01',
    name: 'Armani',
    category: 'Luxury',
    value: '1456'
  },
  {
    date: '2000-01-01',
    name: 'Pampers',
    category: 'FMCG',
    value: '1400'
  },
  {
    date: '2000-01-01',
    name: 'Starbucks',
    category: 'Restaurants',
    value: '1329'
  },
  {
    date: '2000-01-01',
    name: 'Guinness',
    category: 'Alcohol',
    value: '1224'
  },
  {
    date: '2000-01-01',
    name: 'Financial Times',
    category: 'Media',
    value: '1148'
  },
  {
    date: '2000-01-01',
    name: 'Benetton',
    category: 'Apparel',
    value: '1008'
  },
  {
    date: '2001-01-01',
    name: 'Coca-Cola',
    category: 'Beverages',
    value: '68945'
  },
  {
    date: '2001-01-01',
    name: 'Microsoft',
    category: 'Technology',
    value: '65068'
  },
  {
    date: '2001-01-01',
    name: 'IBM',
    category: 'Business Services',
    value: '52752'
  },
  {
    date: '2001-01-01',
    name: 'GE',
    category: 'Diversified',
    value: '42396'
  },
  {
    date: '2001-01-01',
    name: 'Nokia',
    category: 'Technology',
    value: '35035'
  },
  {
    date: '2001-01-01',
    name: 'Intel',
    category: 'Technology',
    value: '34665'
  },
  {
    date: '2001-01-01',
    name: 'Disney',
    category: 'Media',
    value: '32591'
  },
  {
    date: '2001-01-01',
    name: 'Ford',
    category: 'Automotive',
    value: '30092'
  },
  {
    date: '2001-01-01',
    name: "McDonald's",
    category: 'Restaurants',
    value: '25289'
  },
  {
    date: '2001-01-01',
    name: 'AT&T',
    category: 'Telecommunications',
    value: '22828'
  },
  {
    date: '2001-01-01',
    name: 'Marlboro',
    category: 'Tobacco',
    value: '22053'
  },
  {
    date: '2001-01-01',
    name: 'Mercedes-Benz',
    category: 'Automotive',
    value: '21728'
  },
  {
    date: '2001-01-01',
    name: 'Citi',
    category: 'Financial Services',
    value: '19005'
  },
  {
    date: '2001-01-01',
    name: 'Toyota',
    category: 'Automotive',
    value: '18578'
  },
  {
    date: '2001-01-01',
    name: 'HP',
    category: 'Electronics',
    value: '17983'
  },
  {
    date: '2001-01-01',
    name: 'Cisco',
    category: 'Business Services',
    value: '17209'
  },
  {
    date: '2001-01-01',
    name: 'American Express',
    category: 'Financial Services',
    value: '16919'
  },
  {
    date: '2001-01-01',
    name: 'Gillette',
    category: 'FMCG',
    value: '15298'
  },
  {
    date: '2001-01-01',
    name: 'Merrill Lynch',
    category: 'Financial Services',
    value: '15015'
  },
  {
    date: '2001-01-01',
    name: 'Sony',
    category: 'Electronics',
    value: '15005'
  },
  {
    date: '2001-01-01',
    name: 'Honda',
    category: 'Automotive',
    value: '14638'
  },
  {
    date: '2001-01-01',
    name: 'BMW',
    category: 'Automotive',
    value: '13858'
  },
  {
    date: '2001-01-01',
    name: 'NESCAFÉ',
    category: 'Beverages',
    value: '13250'
  },
  {
    date: '2001-01-01',
    name: 'Compaq',
    category: 'Technology',
    value: '12354'
  },
  {
    date: '2001-01-01',
    name: 'Oracle',
    category: 'Business Services',
    value: '12224'
  },
  ... 1875 more items
]

In [11]:
d3.group(data, d => d.name)

InternMap(173) [Map] {
  'Coca-Cola' => [
    {
      date: '2000-01-01',
      name: 'Coca-Cola',
      category: 'Beverages',
      value: '72537'
    },
    {
      date: '2001-01-01',
      name: 'Coca-Cola',
      category: 'Beverages',
      value: '68945'
    },
    {
      date: '2002-01-01',
      name: 'Coca-Cola',
      category: 'Beverages',
      value: '69637'
    },
    {
      date: '2003-01-01',
      name: 'Coca-Cola',
      category: 'Beverages',
      value: '70453'
    },
    {
      date: '2004-01-01',
      name: 'Coca-Cola',
      category: 'Beverages',
      value: '67394'
    },
    {
      date: '2005-01-01',
      name: 'Coca-Cola',
      category: 'Beverages',
      value: '67525'
    },
    {
      date: '2006-01-01',
      name: 'Coca-Cola',
      category: 'Beverages',
      value: '67000'
    },
    {
      date: '2007-01-01',
      name: 'Coca-Cola',
      category: 'Beverages',
      value: '65324'
    },
    {
      date: '2008-01-01',
      name: 'Coca-Cola',
      category: 'Beverages',
      value: '66667'
    },
    {
      date: '2009-01-01',
      name: 'Coca-Cola',
      category: 'Beverages',
      value: '68734'
    },
    {
      date: '2010-01-01',
      name: 'Coca-Cola',
      category: 'Beverages',
      value: '70452'
    },
    {
      date: '2011-01-01',
      name: 'Coca-Cola',
      category: 'Beverages',
      value: '71861'
    },
    {
      date: '2012-01-01',
      name: 'Coca-Cola',
      category: 'Beverages',
      value: '77839'
    },
    {
      date: '2013-01-01',
      name: 'Coca-Cola',
      category: 'Beverages',
      value: '79213'
    },
    {
      date: '2014-01-01',
      name: 'Coca-Cola',
      category: 'Beverages',
      value: '81563'
    },
    {
      date: '2015-01-01',
      name: 'Coca-Cola',
      category: 'Beverages',
      value: '78423'
    },
    {
      date: '2016-01-01',
      name: 'Coca-Cola',
      category: 'Beverages',
      value: '73102'
    },
    {
      date: '2017-01-01',
      name: 'Coca-Cola',
      category: 'Beverages',
      value: '69733'
    },
    {
      date: '2018-01-01',
      name: 'Coca-Cola',
      category: 'Beverages',
      value: '66341'
    },
    {
      date: '2019-01-01',
      name: 'Coca-Cola',
      category: 'Beverages',
      value: '63365'
    }
  ],
  'Microsoft' => [
    {
      date: '2000-01-01',
      name: 'Microsoft',
      category: 'Technology',
      value: '70196'
    },
    {
      date: '2001-01-01',
      name: 'Microsoft',
      category: 'Technology',
      value: '65068'
    },
    {
      date: '2002-01-01',
      name: 'Microsoft',
      category: 'Technology',
      value: '64091'
    },
    {
      date: '2003-01-01',
      name: 'Microsoft',
      category: 'Technology',
      value: '65174'
    },
    {
      date: '2004-01-01',
      name: 'Microsoft',
      category: 'Technology',
      value: '61372'
    },
    {
      date: '2005-01-01',
      name: 'Microsoft',
      category: 'Technology',
      value: '59941'
    },
    {
      date: '2006-01-01',
      name: 'Microsoft',
      category: 'Technology',
      value: '56926'
    },
    {
      date: '2007-01-01',
      name: 'Microsoft',
      category: 'Technology',
      value: '58709'
    },
    {
      date: '2008-01-01',
      name: 'Microsoft',
      category: 'Technology',
      value: '59007'
    },
    {
      date: '2009-01-01',
      name: 'Microsoft',
      category: 'Technology',
      value: '56647'
    },
    {
      date: '2010-01-01',
      name: 'Microsoft',
      category: 'Technology',
      value: '60895'
    },
    {
      date: '2011-01-01',
      name: 'Microsoft',
      category: 'Technology',
      value: '59087'
    },
    {
      date: '2012-01-01',
      name: 'Microsoft',
      category: 'Technology',
      value: '57853'
    },
    {
      date: '2013-01-01',
      name: 'Microsoft',
      category: 'Technology',
      value: '59546'
    },
    {
      date: '2014-01-01',
      name: 'Microsoft',
      category: 'Technology',
      value: '61154'
    },
    {
      date: '2015-01-01',
      name: 'Microsoft',
      category: 'Technology',
      value: '67670'
    },
    {
      date: '2016-01-01',
      name: 'Microsoft',
      category: 'Technology',
      value: '72795'
    },
    {
      date: '2017-01-01',
      name: 'Microsoft',
      category: 'Technology',
      value: '79999'
    },
    {
      date: '2018-01-01',
      name: 'Microsoft',
      category: 'Technology',
      value: '92715'
    },
    {
      date: '2019-01-01',
      name: 'Microsoft',
      category: 'Technology',
      value: '108847'
    }
  ],
  'IBM' => [
    {
      date: '2000-01-01',
      name: 'IBM',
      category: 'Business Services',
      value: '53183'
    },
    {
      date: '2001-01-01',
      name: 'IBM',
      category: 'Business Services',
      value: '52752'
    },
    {
      date: '2002-01-01',
      name: 'IBM',
      category: 'Business Services',
      value: '51188'
    },
    {
      date: '2003-01-01',
      name: 'IBM',
      category: 'Business Services',
      value: '51767'
    },
    {
      date: '2004-01-01',
      name: 'IBM',
      category: 'Business Services',
      value: '53791'
    },
    {
      date: '2005-01-01',
      name: 'IBM',
      category: 'Business Services',
      value: '53376'
    },
    {
      date: '2006-01-01',
      name: 'IBM',
      category: 'Business Services',
      value: '56201'
    },
    {
      date: '2007-01-01',
      name: 'IBM',
      category: 'Business Services',
      value: '57090'
    },
    {
      date: '2008-01-01',
      name: 'IBM',
      category: 'Business Services',
      value: '59031'
    },
    {
      date: '2009-01-01',
      name: 'IBM',
      category: 'Business Services',
      value: '60211'
    },
    {
      date: '2010-01-01',
      name: 'IBM',
      category: 'Business Services',
      value: '64727'
    },
    {
      date: '2011-01-01',
      name: 'IBM',
      category: 'Business Services',
      value: '69905'
    },
    {
      date: '2012-01-01',
      name: 'IBM',
      category: 'Business Services',
      value: '75532'
    },
    {
      date: '2013-01-01',
      name: 'IBM',
      category: 'Business Services',
      value: '78808'
    },
    {
      date: '2014-01-01',
      name: 'IBM',
      category: 'Business Services',
      value: '72244'
    },
    {
      date: '2015-01-01',
      name: 'IBM',
      category: 'Business Services',
      value: '65095'
    },
    {
      date: '2016-01-01',
      name: 'IBM',
      category: 'Business Services',
      value: '52500'
    },
    {
      date: '2017-01-01',
      name: 'IBM',
      category: 'Business Services',
      value: '46829'
    },
    {
      date: '2018-01-01',
      name: 'IBM',
      category: 'Business Services',
      value: '42972'
    },
    {
      date: '2019-01-01',
      name: 'IBM',
      category: 'Business Services',
      value: '40381'
    }
  ],
  'Intel' => [
    {
      date: '2000-01-01',
      name: 'Intel',
      category: 'Technology',
      value: '39048'
    },
    {
      date: '2001-01-01',
      name: 'Intel',
      category: 'Technology',
      value: '34665'
    },
    {
      date: '2002-01-01',
      name: 'Intel',
      category: 'Technology',
      value: '30861'
    },
    {
      date: '2003-01-01',
      name: 'Intel',
      category: 'Technology',
      value: '31112'
    },
    {
      date: '2004-01-01',
      name: 'Intel',
      category: 'Technology',
      value: '33499'
    },
    {
      date: '2005-01-01',
      name: 'Intel',
      category: 'Technology',
      value: '35588'
    },
    {
      date: '2006-01-01',
      name: 'Intel',
      category: 'Technology',
      value: '32319'
    },
    {
      date: '2007-01-01',
      name: 'Intel',
      category: 'Technology',
      value: '30954'
    },
    {
      date: '2008-01-01',
      name: 'Intel',
      category: 'Technology',
      value: '31261'
    },
    {
      date: '2009-01-01',
      name: 'Intel',
      category: 'Technology',
      value: '30636'
    },
    {
      date: '2010-01-01',
      name: 'Intel',
      category: 'Technology',
      value: '32015'
    },
    {
      date: '2011-01-01',
      name: 'Intel',
      category: 'Technology',
      value: '35217'
    },
    {
      date: '2012-01-01',
      name: 'Intel',
      category: 'Technology',
      value: '39385'
    },
    {
      date: '2013-01-01',
      name: 'Intel',
      category: 'Technology',
      value: '37257'
    },
    {
      date: '2014-01-01',
      name: 'Intel',
      category: 'Technology',
      value: '34153'
    },
    {
      date: '2015-01-01',
      name: 'Intel',
      category: 'Technology',
      value: '35415'
    },
    {
      date: '2016-01-01',
      name: 'Intel',
      category: 'Technology',
      value: '36952'
    },
    {
      date: '2017-01-01',
      name: 'Intel',
      category: 'Technology',
      value: '39459'
    },
    {
      date: '2018-01-01',
      name: 'Intel',
      category: 'Technology',
      value: '43293'
    },
    {
      date: '2019-01-01',
      name: 'Intel',
      category: 'Technology',
      value: '40197'
    }
  ],
  'Nokia' => [
    {
      date: '2000-01-01',
      name: 'Nokia',
      category: 'Technology',
      value: '38528'
    },
    {
      date: '2001-01-01',
      name: 'Nokia',
      category: 'Technology',
      value: '35035'
    },
    {
      date: '2002-01-01',
      name: 'Nokia',
      category: 'Technology',
      value: '29970'
    },
    {
      date: '2003-01-01',
      name: 'Nokia',
      category: 'Technology',
      value: '29440'
    },
    {
      date: '2004-01-01',
      name: 'Nokia',
      category: 'Technology',
      value: '24041'
    },
    {
      date: '2005-01-01',
      name: 'Nokia',
      category: 'Technology',
      value: '26452'
    },
    {
      date: '2006-01-01',
      name: 'Nokia',
      category: 'Technology',
      value: '30131'
    },
    {
      date: '2007-01-01',
      name: 'Nokia',
      category: 'Technology',
      value: '33696'
    },
    {
      date: '2008-01-01',
      name: 'Nokia',
      category: 'Technology',
      value: '35942'
    },
    {
      date: '2009-01-01',
      name: 'Nokia',
      category: 'Technology',
      value: '34864'
    },
    {
      date: '2010-01-01',
      name: 'Nokia',
      category: 'Technology',
      value: '29495'
    },
    {
      date: '2011-01-01',
      name: 'Nokia',
      category: 'Technology',
      value: '25071'
    },
    {
      date: '2012-01-01',
      name: 'Nokia',
      category: 'Technology',
      value: '21009'
    },
    {
      date: '2013-01-01',
      name: 'Nokia',
      category: 'Technology',
      value: '7444'
    },
    {
      date: '2014-01-01',
      name: 'Nokia',
      category: 'Technology',
      value: '4138'
    }
  ],
  'GE' => [
    {
      date: '2000-01-01',
      name: 'GE',
      category: 'Diversified',
      value: '38127'
    },
    {
      date: '2001-01-01',
      name: 'GE',
      category: 'Diversified',
      value: '42396'
    },
    {
      date: '2002-01-01',
      name: 'GE',
      category: 'Diversified',
      value: '41311'
    },
    {
      date: '2003-01-01',
      name: 'GE',
      category: 'Diversified',
      value: '42340'
    },
    {
      date: '2004-01-01',
      name: 'GE',
      category: 'Diversified',
      value: '44111'
    },
    {
      date: '2005-01-01',
      name: 'GE',
      category: 'Diversified',
      value: '46996'
    },
    {
      date: '2006-01-01',
      name: 'GE',
      category: 'Diversified',
      value: '48907'
    },
    {
      date: '2007-01-01',
      name: 'GE',
      category: 'Diversified',
      value: '51569'
    },
    {
      date: '2008-01-01',
      name: 'GE',
      category: 'Diversified',
      value: '53086'
    },
    {
      date: '2009-01-01',
      name: 'GE',
      category: 'Diversified',
      value: '47777'
    },
    {
      date: '2010-01-01',
      name: 'GE',
      category: 'Diversified',
      value: '42808'
    },
    {
      date: '2011-01-01',
      name: 'GE',
      category: 'Diversified',
      value: '42808'
    },
    {
      date: '2012-01-01',
      name: 'GE',
      category: 'Diversified',
      value: '43682'
    },
    {
      date: '2013-01-01',
      name: 'GE',
      category: 'Diversified',
      value: '46947'
    },
    {
      date: '2014-01-01',
      name: 'GE',
      category: 'Diversified',
      value: '45480'
    },
    {
      date: '2015-01-01',
      name: 'GE',
      category: 'Diversified',
      value: '42267'
    },
    {
      date: '2016-01-01',
      name: 'GE',
      category: 'Diversified',
      value: '43130'
    },
    {
      date: '2017-01-01',
      name: 'GE',
      category: 'Diversified',
      value: '44208'
    },
    {
      date: '2018-01-01',
      name: 'GE',
      category: 'Diversified',
      value: '32757'
    },
    {
      date: '2019-01-01',
      name: 'GE',
      category: 'Diversified',
      value: '25566'
    }
  ],
  'Ford' => [
    {
      date: '2000-01-01',
      name: 'Ford',
      category: 'Automotive',
      value: '36368'
    },
    {
      date: '2001-01-01',
      name: 'Ford',
      category: 'Automotive',
      value: '30092'
    },
    {
      date: '2002-01-01',
      name: 'Ford',
      category: 'Automotive',
      value: '20403'
    },
    {
      date: '2003-01-01',
      name: 'Ford',
      category: 'Automotive',
      value: '17066'
    },
    {
      date: '2004-01-01',
      name: 'Ford',
      category: 'Automotive',
      value: '14475'
    },
    {
      date: '2005-01-01',
      name: 'Ford',
      category: 'Automotive',
      value: '13159'
    },
    {
      date: '2006-01-01',
      name: 'Ford',
      category: 'Automotive',
      value: '11056'
    },
    {
      date: '2007-01-01',
      name: 'Ford',
      category: 'Automotive',
      value: '8982'
    },
    {
      date: '2008-01-01',
      name: 'Ford',
      category: 'Automotive',
      value: '7896'
    },
    {
      date: '2009-01-01',
      name: 'Ford',
      category: 'Automotive',
      value: '7005'
    },
    {
      date: '2010-01-01',
      name: 'Ford',
      category: 'Automotive',
      value: '7195'
    },
    {
      date: '2011-01-01',
      name: 'Ford',
      category: 'Automotive',
      value: '7483'
    },
    {
      date: '2012-01-01',
      name: 'Ford',
      category: 'Automotive',
      value: '7958'
    },
    {
      date: '2013-01-01',
      name: 'Ford',
      category: 'Automotive',
      value: '9181'
    },
    {
      date: '2014-01-01',
      name: 'Ford',
      category: 'Automotive',
      value: '10876'
    },
    {
      date: '2015-01-01',
      name: 'Ford',
      category: 'Automotive',
      value: '11578'
    },
    {
      date: '2016-01-01',
      name: 'Ford',
      category: 'Automotive',
      value: '12962'
    },
    {
      date: '2017-01-01',
      name: 'Ford',
      category: 'Automotive',
      value: '13643'
    },
    {
      date: '2018-01-01',
      name: 'Ford',
      category: 'Automotive',
      value: '13995'
    },
    {
      date: '2019-01-01',
      name: 'Ford',
      category: 'Automotive',
      value: '14325'
    }
  ],
  'Disney' => [
    {
      date: '2000-01-01',
      name: 'Disney',
      category: 'Media',
      value: '33553'
    },
    {
      date: '2001-01-01',
      name: 'Disney',
      category: 'Media',
      value: '32591'
    },
    {
      date: '2002-01-01',
      name: 'Disney',
      category: 'Media',
      value: '29256'
    },
    {
      date: '2003-01-01',
      name: 'Disney',
      category: 'Media',
      value: '28036'
    },
    {
      date: '2004-01-01',
      name: 'Disney',
      category: 'Media',
      value: '27113'
    },
    {
      date: '2005-01-01',
      name: 'Disney',
      category: 'Media',
      value: '26441'
    },
    {
      date: '2006-01-01',
      name: 'Disney',
      category: 'Media',
      value: '27848'
    },
    {
      date: '2007-01-01',
      name: 'Disney',
      category: 'Media',
      value: '29210'
    },
    {
      date: '2008-01-01',
      name: 'Disney',
      category: 'Media',
      value: '29251'
    },
    {
      date: '2009-01-01',
      name: 'Disney',
      category: 'Media',
      value: '28447'
    },
    {
      date: '2010-01-01',
      name: 'Disney',
      category: 'Media',
      value: '28731'
    },
    {
      date: '2011-01-01',
      name: 'Disney',
      category: 'Media',
      value: '29018'
    },
    {
      date: '2012-01-01',
      name: 'Disney',
      category: 'Media',
      value: '27438'
    },
    {
      date: '2013-01-01',
      name: 'Disney',
      category: 'Media',
      value: '28147'
    },
    {
      date: '2014-01-01',
      name: 'Disney',
      category: 'Media',
      value: '32223'
    },
    {
      date: '2015-01-01',
      name: 'Disney',
      category: 'Media',
      value: '36514'
    },
    {
      date: '2016-01-01',
      name: 'Disney',
      category: 'Media',
      value: '38790'
    },
    {
      date: '2017-01-01',
      name: 'Disney',
      category: 'Media',
      value: '40772'
    },
    {
      date: '2018-01-01',
      name: 'Disney',
      category: 'Media',
      value: '39874'
    },
    {
      date: '2019-01-01',
      name: 'Disney',
      category: 'Media',
      value: '44352'
    }
  ],
  "McDonald's" => [
    {
      date: '2000-01-01',
      name: "McDonald's",
      category: 'Restaurants',
      value: '27859'
    },
    {
      date: '2001-01-01',
      name: "McDonald's",
      category: 'Restaurants',
      value: '25289'
    },
    {
      date: '2002-01-01',
      name: "McDonald's",
      category: 'Restaurants',
      value: '26375'
    },
    {
      date: '2003-01-01',
      name: "McDonald's",
      category: 'Restaurants',
      value: '24699'
    },
    {
      date: '2004-01-01',
      name: "McDonald's",
      category: 'Restaurants',
      value: '25001'
    },
    {
      date: '2005-01-01',
      name: "McDonald's",
      category: 'Restaurants',
      value: '26014'
    },
    {
      date: '2006-01-01',
      name: "McDonald's",
      category: 'Restaurants',
      value: '27501'
    },
    {
      date: '2007-01-01',
      name: "McDonald's",
      category: 'Restaurants',
      value: '29398'
    },
    {
      date: '2008-01-01',
      name: "McDonald's",
      category: 'Restaurants',
      value: '31049'
    },
    {
      date: '2009-01-01',
      name: "McDonald's",
      category: 'Restaurants',
      value: '32275'
    },
    {
      date: '2010-01-01',
      name: "McDonald's",
      category: 'Restaurants',
      value: '33578'
    },
    {
      date: '2011-01-01',
      name: "McDonald's",
      category: 'Restaurants',
      value: '35593'
    },
    {
      date: '2012-01-01',
      name: "McDonald's",
      category: 'Restaurants',
      value: '40062'
    },
    {
      date: '2013-01-01',
      name: "McDonald's",
      category: 'Restaurants',
      value: '41992'
    },
    {
      date: '2014-01-01',
      name: "McDonald's",
      category: 'Restaurants',
      value: '42254'
    },
    {
      date: '2015-01-01',
      name: "McDonald's",
      category: 'Restaurants',
      value: '39809'
    },
    {
      date: '2016-01-01',
      name: "McDonald's",
      category: 'Restaurants',
      value: '39381'
    },
    {
      date: '2017-01-01',
      name: "McDonald's",
      category: 'Restaurants',
      value: '41533'
    },
    {
      date: '2018-01-01',
      name: "McDonald's",
      category: 'Restaurants',
      value: '43417'
    },
    {
      date: '2019-01-01',
      name: "McDonald's",
      category: 'Restaurants',
      value: '45362'
    }
  ],
  'AT&T' => [
    {
      date: '2000-01-01',
      name: 'AT&T',
      category: 'Telecommunications',
      value: '25548'
    },
    {

In [12]:
data.filter(d => d.name === "Heineken")

[
  {
    date: '2000-01-01',
    name: 'Heineken',
    category: 'Alcohol',
    value: '2218'
  },
  {
    date: '2001-01-01',
    name: 'Heineken',
    category: 'Alcohol',
    value: '2266'
  },
  {
    date: '2002-01-01',
    name: 'Heineken',
    category: 'Alcohol',
    value: '2396'
  },
  {
    date: '2003-01-01',
    name: 'Heineken',
    category: 'Alcohol',
    value: '2431'
  },
  {
    date: '2004-01-01',
    name: 'Heineken',
    category: 'Alcohol',
    value: '2380'
  },
  {
    date: '2005-01-01',
    name: 'Heineken',
    category: 'Alcohol',
    value: '2357'
  },
  {
    date: '2010-01-01',
    name: 'Heineken',
    category: 'Alcohol',
    value: '3516'
  },
  {
    date: '2011-01-01',
    name: 'Heineken',
    category: 'Alcohol',
    value: '3809'
  },
  {
    date: '2012-01-01',
    name: 'Heineken',
    category: 'Alcohol',
    value: '3939'
  },
  {
    date: '2013-01-01',
    name: 'Heineken',
    category: 'Alcohol',
    value: '4331'
  },
  {
    date: '2014-01-01',
    name: 'Heineken',
    category: 'Alcohol',
    value: '4221'
  },
  {
    date: '2015-01-01',
    name: 'Heineken',
    category: 'Alcohol',
    value: '4822'
  },
  {
    date: '2016-01-01',
    name: 'Heineken',
    category: 'Alcohol',
    value: '5123'
  },
  {
    date: '2017-01-01',
    name: 'Heineken',
    category: 'Alcohol',
    value: '5181'
  },
  {
    date: '2018-01-01',
    name: 'Heineken',
    category: 'Alcohol',
    value: '5393'
  },
  {
    date: '2019-01-01',
    name: 'Heineken',
    category: 'Alcohol',
    value: '5626'
  }
]

In [13]:
n = 12

12

In [14]:
names = new Set(data.map(d => d.name))

Set(173) {
  'Coca-Cola',
  'Microsoft',
  'IBM',
  'Intel',
  'Nokia',
  'GE',
  'Ford',
  'Disney',
  "McDonald's",
  'AT&T',
  'Marlboro',
  'Mercedes-Benz',
  'HP',
  'Cisco',
  'Toyota',
  'Citi',
  'Gillette',
  'Sony',
  'American Express',
  'Honda',
  'Compaq',
  'NESCAFÉ',
  'BMW',
  'Kodak',
  'Heinz',
  'Budweiser',
  'Xerox',
  'Dell',
  'Gap',
  'Nike',
  'Volkswagen',
  'Ericsson',
  "Kellogg's",
  'Louis Vuitton',
  'Pepsi',
  'Apple',
  'MTV',
  'Yahoo!',
  'SAP',
  'IKEA',
  'Duracell',
  'Philips',
  'Samsung',
  'Gucci',
  'Kleenex',
  'Reuters',
  'AOL',
  'Amazon',
  'Motorola',
  'Colgate',
  'Wrigley',
  'Chanel',
  'adidas',
  'Panasonic',
  'Rolex',
  'Hertz',
  'Bacardi',
  'BP',
  'Moët & Chandon',
  'Shell',
  'Burger King',
  'Smirnoff',
  'Barbie',
  'Heineken',
  'Wall Street Journal',
  'Ralph Lauren',
  'Johnnie Walker',
  'Hilton',
  "Jack Daniel's",
  'Armani',
  'Pampers',
  'Starbucks',
  'Guinness',
  'Financial Times',
  'Benetton',
  'Merrill Lynch',
  'Oracle',
  'Merck & Co., Inc.',
  'Nintendo',
  'Pfizer',
  'Goldman Sachs',
  'Canon',
  'Pizza Hut',
  'Harley-Davidson',
  'KFC',
  'Sun Microsystems',
  'Avon',
  'Boeing',
  'Texas Instruments',
  'Kraft',
  "Levi's",
  'Time',
  'Tiffany & Co.',
  'Mobil',
  'FedEx',
  'Nivea',
  'Absolut',
  'Carlsberg',
  'Siemens',
  'Swatch',
  ... 73 more items
}

In [23]:
datevalues = Array.from(d3.rollup(data, ([d]) => d.value, d => d.date, d => d.name))
    .map(([date, data]) => [new Date(date), data])
    .sort(([a], [b]) => d3.ascending(a, b))

[
  [
    2000-01-01T00:00:00.000Z,
    InternMap(75) [Map] {
      'Coca-Cola' => '72537',
      'Microsoft' => '70196',
      'IBM' => '53183',
      'Intel' => '39048',
      'Nokia' => '38528',
      'GE' => '38127',
      'Ford' => '36368',
      'Disney' => '33553',
      "McDonald's" => '27859',
      'AT&T' => '25548',
      'Marlboro' => '22110',
      'Mercedes-Benz' => '21104',
      'HP' => '20572',
      'Cisco' => '20067',
      'Toyota' => '18823',
      'Citi' => '18809',
      'Gillette' => '17358',
      'Sony' => '16409',
      'American Express' => '16122',
      'Honda' => '15244',
      'Compaq' => '14602',
      'NESCAFÉ' => '13680',
      'BMW' => '12969',
      'Kodak' => '11822',
      'Heinz' => '11742',
      'Budweiser' => '10684',
      'Xerox' => '9699',
      'Dell' => '9476',
      'Gap' => '9316',
      'Nike' => '8015',
      'Volkswagen' => '7834',
      'Ericsson' => '7805',
      "Kellogg's" => '7357',
      'Louis Vuitton' => '6887',
      'Pepsi' => '6636',
      'Apple' => '6594',
      'MTV' => '6411',
      'Yahoo!' => '6299',
      'SAP' => '6135',
      'IKEA' => '6031',
      'Duracell' => '5885',
      'Philips' => '5481',
      'Samsung' => '5223',
      'Gucci' => '5149',
      'Kleenex' => '5144',
      'Reuters' => '4876',
      'AOL' => '4531',
      'Amazon' => '4528',
      'Motorola' => '4445',
      'Colgate' => '4417',
      'Wrigley' => '4324',
      'Chanel' => '4141',
      'adidas' => '3791',
      'Panasonic' => '3734',
      'Rolex' => '3561',
      'Hertz' => '3438',
      'Bacardi' => '3187',
      'BP' => '3066',
      'Moët & Chandon' => '2799',
      'Shell' => '2786',
      'Burger King' => '2701',
      'Smirnoff' => '2443',
      'Barbie' => '2315',
      'Heineken' => '2218',
      'Wall Street Journal' => '2184',
      'Ralph Lauren' => '1834',
      'Johnnie Walker' => '1541',
      'Hilton' => '1483',
      "Jack Daniel's" => '1480',
      'Armani' => '1456',
      'Pampers' => '1400',
      'Starbucks' => '1329',
      'Guinness' => '1224',
      'Financial Times' => '1148',
      'Benetton' => '1008'
    }
  ],
  [
    2001-01-01T00:00:00.000Z,
    InternMap(100) [Map] {
      'Coca-Cola' => '68945',
      'Microsoft' => '65068',
      'IBM' => '52752',
      'GE' => '42396',
      'Nokia' => '35035',
      'Intel' => '34665',
      'Disney' => '32591',
      'Ford' => '30092',
      "McDonald's" => '25289',
      'AT&T' => '22828',
      'Marlboro' => '22053',
      'Mercedes-Benz' => '21728',
      'Citi' => '19005',
      'Toyota' => '18578',
      'HP' => '17983',
      'Cisco' => '17209',
      'American Express' => '16919',
      'Gillette' => '15298',
      'Merrill Lynch' => '15015',
      'Sony' => '15005',
      'Honda' => '14638',
      'BMW' => '13858',
      'NESCAFÉ' => '13250',
      'Compaq' => '12354',
      'Oracle' => '12224',
      'Budweiser' => '10838',
      'Kodak' => '10801',
      'Merck & Co., Inc.' => '9672',
      'Nintendo' => '9460',
      'Pfizer' => '8951',
      'Gap' => '8746',
      'Dell' => '8269',
      'Goldman Sachs' => '7862',
      'Nike' => '7589',
      'Volkswagen' => '7338',
      'Ericsson' => '7069',
      'Heinz' => '7062',
      'Louis Vuitton' => '7053',
      "Kellogg's" => '7005',
      'MTV' => '6599',
      'Canon' => '6580',
      'Samsung' => '6374',
      'SAP' => '6307',
      'Pepsi' => '6214',
      'Xerox' => '6019',
      'IKEA' => '6005',
      'Pizza Hut' => '5978',
      'Harley-Davidson' => '5532',
      'Apple' => '5464',
      'Gucci' => '5363',
      'KFC' => '5261',
      'Reuters' => '5236',
      'Sun Microsystems' => '5149',
      'Kleenex' => '5085',
      'Philips' => '4900',
      'Colgate' => '4572',
      'Wrigley' => '4530',
      'AOL' => '4495',
      'Yahoo!' => '4378',
      'Avon' => '4369',
      'Chanel' => '4265',
      'Duracell' => '4140',
      'Boeing' => '4060',
      'Texas Instruments' => '4041',
      'Kraft' => '4032',
      'Motorola' => '3761',
      "Levi's" => '3747',
      'Time' => '3724',
      'Rolex' => '3701',
      'adidas' => '3650',
      'Hertz' => '3617',
      'Panasonic' => '3490',
      'Tiffany & Co.' => '3483',
      'BP' => '3247',
      'Bacardi' => '3204',
      'Amazon' => '3130',
      'Shell' => '2844',
      'Smirnoff' => '2594',
      'Moët & Chandon' => '2470',
      'Burger King' => '2426',
      'Mobil' => '2415',
      'Heineken' => '2266',
      'Wall Street Journal' => '2184',
      'Barbie' => '2037',
      'Ralph Lauren' => '1910',
      'FedEx' => '1885',
      'Nivea' => '1782',
      'Starbucks' => '1757',
      'Johnnie Walker' => '1649',
      "Jack Daniel's" => '1583',
      'Armani' => '1490',
      'Pampers' => '1410',
      'Absolut' => '1378',
      'Guinness' => '1357',
      'Financial Times' => '1310',
      'Hilton' => '1235',
      'Carlsberg' => '1075',
      'Siemens' => '1029',
      'Swatch' => '1004',
      'Benetton' => '1002'
    }
  ],
  [
    2002-01-01T00:00:00.000Z,
    InternMap(100) [Map] {
      'Coca-Cola' => '69637',
      'Microsoft' => '64091',
      'IBM' => '51188',
      'GE' => '41311',
      'Intel' => '30861',
      'Nokia' => '29970',
      'Disney' => '29256',
      "McDonald's" => '26375',
      'Marlboro' => '24151',
      'Mercedes-Benz' => '21010',
      'Ford' => '20403',
      'Toyota' => '19448',
      'Citi' => '18066',
      'HP' => '16776',
      'American Express' => '16287',
      'Cisco' => '16222',
      'AT&T' => '16059',
      'Honda' => '15064',
      'Gillette' => '14959',
      'BMW' => '14425',
      'Sony' => '13899',
      'NESCAFÉ' => '12843',
      'Oracle' => '11510',
      'Budweiser' => '11349',
      'Merrill Lynch' => '11230',
      'Morgan Stanley' => '11205',
      'Compaq' => '9803',
      'Pfizer' => '9770',
      'J.P. Morgan' => '9693',
      'Kodak' => '9671',
      'Dell' => '9237',
      'Nintendo' => '9219',
      'Merck & Co., Inc.' => '9138',
      'Samsung' => '8310',
      'Nike' => '7724',
      'Gap' => '7406',
      'Heinz' => '7347',
      'Volkswagen' => '7209',
      'Goldman Sachs' => '7194',
      "Kellogg's" => '7191',
      'Louis Vuitton' => '7054',
      'SAP' => '6775',
      'Canon' => '6721',
      'IKEA' => '6545',
      'Pepsi' => '6394',
      'Harley-Davidson' => '6266',
      'MTV' => '6078',
      'Pizza Hut' => '6046',
      'KFC' => '5346',
      'Apple' => '5316',
      'Xerox' => '5308',
      'Gucci' => '5304',
      'Accenture' => '5182',
      "L'Oréal" => '5079',
      'Kleenex' => '5039',
      'Sun Microsystems' => '4773',
      'Wrigley' => '4747',
      'Reuters' => '4611',
      'Colgate' => '4602',
      'Philips' => '4561',
      'Nestlé' => '4430',
      'Avon' => '4399',
      'AOL' => '4326',
      'Chanel' => '4272',
      'Kraft' => '4079',
      'Danone' => '4054',
      'Yahoo!' => '3855',
      'adidas' => '3690',
      'Rolex' => '3686',
      'Time' => '3682',
      'Ericsson' => '3589',
      'Tiffany & Co.' => '3482',
      "Levi's" => '3454',
      'Motorola' => '3416',
      'Duracell' => '3409',
      'BP' => '3390',
      'Hertz' => '3362',
      'Bacardi' => '3341',
      'Caterpillar' => '3218',
      'Amazon' => '3175',
      'Panasonic' => '3141',
      'Boeing' => '2973',
      'Shell' => '2810',
      'Smirnoff' => '2723',
      'Johnson & Johnson' => '2509',
      'Prada' => '2489',
      'Moët & Chandon' => '2445',
      'Heineken' => '2396',
      'Mobil' => '2358',
      'Burger King' => '2163',
      'Nivea' => '2059',
      'Wall Street Journal' => '1961',
      'Starbucks' => '1961',
      'Barbie' => '1937',
      'Ralph Lauren' => '1928',
      'FedEx' => '1919',
      'Johnnie Walker' => '1654',
      "Jack Daniel's" => '1580',
      '3M' => '1579',
      'Armani' => '1509'
    }
  ],
  [
    2003-01-01T00:00:00.000Z,
    InternMap(100) [Map] {
      'Coca-Cola' => '70453',
      'Microsoft' => '65174',
      'IBM' => '51767',
      'GE' => '42340',
      'Intel' => '31112',
      'Nokia' => '29440',
      'Disney' => '28036',
      "McDonald's" => '24699',
      'Marlboro' => '22183',
      'Mercedes-Benz' => '21371',
      'Toyota' => '20784',
      'HP' => '19860',
      'Citi' => '18571',
      'Ford' => '17066',
      'American Express' => '16833',
      'Gillette' => '15978',
      'Cisco' => '15789',
      'Honda' => '15625',
      'BMW' => '15106',
      'Sony' => '13153',
      'NESCAFÉ' => '12336',
      'Budweiser' => '11894',
      'Pepsi' => '11777',
      'Oracle' => '11263',
      'Samsung' => '10846',
      'Morgan Stanley' => '10691',
      'Merrill Lynch' => '10521',
      'Pfizer' => '10455',
      'Dell' => '10367',
      'Merck & Co., Inc.' => '9407',
      'J.P. Morgan' => '9120',
      'Nintendo' => '8190',
      'Nike' => '8167',
      'Kodak' => '7826',
      'SAP' => '7714',
      'Gap' => '7688',
      'HSBC' => '7565',
      "Kellogg's" => '7438',
      'Canon' => '7192',
      'Heinz' => '7097',
      'Goldman Sachs' => '7039',
      'Volkswagen' => '6938',
      'IKEA' => '6918',
      'Harley-Davidson' => '6775',
      'Louis Vuitton' => '6708',
      'MTV' => '6278',
      "L'Oréal" => '5600',
      'Xerox' => '5578',
      'KFC' => '5576',
      'Apple' => '5554',
      'Pizza Hut' => '5312',
      'Accenture' => '5301',
      'Gucci' => '5100',
      'Kleenex' => '5057',
      'Wrigley' => '5057',
      'Colgate' => '4686',
      'Avon' => '4631',
      'Sun Microsystems' => '4465',
      'Philips' => '4464',
      'Nestlé' => '4460',
      'Chanel' => '4315',
      'Danone' => '4237',
      'Kraft' => '4171',
      'AOL' => '3961',
      'Yahoo!' => '3895',
      'Time' => '3784',
      'adidas' => '3679',
      'Rolex' => '3673',
      'BP' => '3582',
      'Tiffany & Co.' => '3540',
      'Duracell' => '3438',
      'Bacardi' => '3431',
      'Hermès' => '3416',
      'Amazon' => '3403',
      'Caterpillar' => '3363',
      'Reuters' => '3300',
      "Levi's" => '3298',
      'Hertz' => '3288',
      'Panasonic' => '3257',
      'Ericsson' => '3153',
      'Motorola' => '3103',
      'Hennessy' => '2996',
      'Shell' => '2983',
      'Boeing' => '2864',
      'Smirnoff' => '2806',
      'Johnson & Johnson' => '2706',
      'Prada' => '2535',
      'Moët & Chandon' => '2524',
      'Nissan' => '2495',
      'Heineken' => '2431',
      'Mobil' => '2407',
      'Nivea' => '2221',
      'Starbucks' => '2136',
      'Burger King' => '2121',
      'Ralph Lauren' => '2048',
      'FedEx' => '2032',
      'Barbie' => '1873',
      'Wall Street Journal' => '1763',
      'Johnnie Walker' => '1724',
      "Jack Daniel's" => '1612'
    }
  ],
  [
    2004-01-01T00:00:00.000Z,
    InternMap(100) [Map] {
      'Coca-Cola' => '67394',
      'Microsoft' => '61372',
      'IBM' => '53791',
      'GE' => '44111',
      'Intel' => '33499',
      'Disney' => '27113',
      "McDonald's" => '25001',
      'Nokia' => '24041',
      'Toyota' => '22673',
      'Marlboro' => '22128',
      'Mercedes-Benz' => '21331',
      'HP' => '20978',
      'Citi' => '19971',
      'American Express' => '17683',
      'Gillette' => '16723',
      'Cisco' => '15948',
      'BMW' => '15886',
      'Honda' => '14874',
      'Ford' => '14475',
      'Sony' => '12759',
      'Samsung' => '12553',
      'Pepsi' => '12066',
      'NESCAFÉ' => '11892',
      'Budweiser' => '11846',
      'Dell' => '11500',
      'Merrill Lynch' => '11499',
      'Morgan Stanley' => '11498',
      'Oracle' => '10935',
      'Pfizer' => '10635',
      'J.P. Morgan' => '9782',
      'Nike' => '9260',
      'Merck & Co., Inc.' => '8811',
      'HSBC' => '8671',
      'SAP' => '8323',
      'Canon' => '8055',
      "Kellogg's" => '8029',
      'Goldman Sachs' => '7954',
      'Gap' => '7873',
      'Siemens' => '7470',
      'IKEA' => '7182',
      'Harley-Davidson' => '7057',
      'Heinz' => '7026',
      'Apple' => '6871',
      'Louis Vuitton' => '6602',
      'UBS' => '6526',
      'Nintendo' => '6479',
      'MTV' => '6456',
      'Volkswagen' => '6410',
      "L'Oréal" => '5902',
      'Accenture' => '5772',
      'Xerox' => '5696',
      'Wrigley' => '5424',
      'Kodak' => '5231',
      'KFC' => '5118',
      'Pizza Hut' => '5050',
      'Colgate' => '4929',
      'Kleenex' => '4881',
      'Avon' => '4849',
      'Gucci' => '4715',
      'eBay' => '4700',
      'Yahoo!' => '4545',
      'Nestlé' => '4529',
      'Danone' => '4488',
      'Chanel' => '4416',
      'Philips' => '4378',
      'Amazon' => '4156',
      'Kraft' => '4112',
      'Caterpillar' => '3801',
      'adidas' => '3740',
      'Rolex' => '3720',
      'Reuters' => '3691',
      'BP' => '3662',
      'Time' => '3651',
      'Porsche' => '3646',
      'Tiffany & Co.' => '3638',
      'Motorola' => '3483',
      'Panasonic' => '3480',
      'Hertz' => '3411',
      'Hermès' => '3376',
      'Duracell' => '3362',
      'Audi' => '3288',
      'AOL' => '3248',
      'Hennessy' => '3084',
      'Shell' => '2985',
      "Levi's" => '2979',
      'Smirnoff' => '2975',
      'Johnson & Johnson' => '2952',
      'ING' => '2864',
      'Moët & Chandon' => '2861',
      'Nissan' => '2833',
      'Cartier' => '2749',
      'Estee Lauder' => '2634',
      'Armani' => '2613',
      'Boeing' => '2576',
      'Prada' => '2568',
      'Mobil' => '2492',
      'Nivea' => '2409',
      'Starbucks' => '2400',
      'Heineken' => '2380',
      'Ralph Lauren' => '2147'
    }
  ],
  [
    2005-01-01T00:00:00.000Z,
    InternMap(100) [Map] {
      'Coca-Cola' => '67525',
      'Microsoft' => '59941',
      'IBM' => '53376',
      'GE' => '46996',
      'Intel' => '35588',
      'Nokia' => '26452',
      'Disney' => '26441',
      "McDonald's" => '26014',
      'Toyota' => '24837',
      'Marlboro' => '21189',
      'Mercedes-Benz' => '20006',
      'Citi' => '19967',
      'HP' => '18866',
      'American Express' => '18559',
      'Gillette' => '17534',
      'BMW' => '17126',
      'Cisco' => '16592',
      'Louis Vuitton' => '16077',
      'Honda' => '15788',
      'Samsung' => '14956',
      'Dell' => '13231',
      'Ford' => '13159',
      'Pepsi' => '12399',
      'NESCAFÉ' => '12241',
      'Merrill Lynch' => '12018',
      'Budweiser' => '11878',
      'Oracle' => '10887',
      'Sony' => '10754',
      'HSBC' => '10429',
      'Nike' => '10114',
      'Pfizer' => '9981',
      'UPS' => '9923',
      'Morgan Stanley' => '9777',
      'J.P. Morgan' => '9455',
      'Canon' => '9044',
      'SAP' => '9006',
      'Goldman Sachs' => '8495',
      'Google' => '8461',
      "Kellogg's" => '8306',
      'Gap' => '8195',
      'Apple' => '7985',
      'IKEA' => '7817',
      'Novartis' => '7746',
      'UBS' => '7565',
      'Siemens' => '7507',
      'Harley-Davidson' => '7346',
      'Heinz' => '6932',
      'MTV' => '6647',
      'Gucci' => '6619',
      'Nintendo' => '6470',
      'Accenture' => '6142',
      "L'Oréal" => '6005',
      'Philips' => '5901',
      'Xerox' => '5705',
      'eBay' => '5701',
      'Volkswagen' => '5617',
      'Wrigley' => '5543',
      'Yahoo!' => '5256',
      'Avon' => '5213',
      'Colgate' => '5186',
      'KFC' => '5112',
      'Kodak' => '4979',
      'Pizza Hut' => '4963',
      'Kleenex' => '4922',
      'Chanel' => '4778',
      'Nestlé' => '4744',
      'Danone' => '4513',
      'Amazon' => '4248',
      'Kraft' => '4238',
      'Caterpillar' => '4085',
      'adidas' => '4033',
      'Rolex' => '3906',
      'Motorola' => '3877',
      'Reuters' => '3866',
      'BP' => '3802',
      'Porsche' => '3777',
      'Zara' => '3730',
      'Panasonic' => '3714',
      'Audi' => '3686',
      'Duracell' => '3679',
      'Tiffany & Co.' => '3618',
      'Hermès' => '3540',
      'Hertz' => '3521',
      'Hyundai' => '3480',
      'Nissan' => '3203',
      'Hennessy' => '3201',
      'ING' => '3177',
      'Smirnoff' => '3097',
      'Cartier' => '3050',
      'Shell' => '3048',
      'Johnson & Johnson' => '3040',
      'Moët & Chandon' => '2991',
      'Prada' => '2760',
      'Bulgari' => '2715',
      'Armani' => '2677',
      "Levi's" => '2655',
      'LG' => '2645',
      'Nivea' => '2576',
      'Starbucks' => '2576',
      'Heineken' => '2357'
    }
  ],
  [
    2006-01-01T00:00:00.000Z,
    InternMap(100) [Map] {
      'Coca-Cola' => '67000',
      'Microsoft' => '56926',
      'IBM' => '56201',
      'GE' => '48907',
      'Intel' => '32319',
      'Nokia' => '30131',
      'Toyota' => '27941',
      'Disney' => '27848',
      "McDonald's" => '27501',
      'Mercedes-Benz' => '21795',
      'Citi' => '21458',
      'Marlboro' => '21350',
      'HP' => '20458',
      'American Express' => '19641',
      'BMW' => '19617',
      'Gillette' => '19579',
      'Louis Vuitton' => '17606',
      'Cisco' => '17532',
      'Honda' => '17049',
      'Samsung' => '16169',
      'Merrill Lynch' => '13001',
      'Pepsi' => '12690',
      'NESCAFÉ' => '12507',
      'Google' => '12376',
      'Dell' => '12256',
      'Sony' => '11695',
      'Budweiser' => '11662',
      'HSBC' => '11622',
      'Oracle' => '11459',
      'Ford' => '11056',
      'Nike' => '10897',
      'UPS' => '10712',
      'J.P. Morgan' => '10205',
      'SAP' => '10007',
      'Canon' => '9968',
      'Morgan Stanley' => '9762',
      'Goldman Sachs' => '9640',
      'Pfizer' => '9591',
      'Apple' => '9130',
      "Kellogg's" => '8776',
      'IKEA' => '8763',
      'UBS' => '8734',
      'Novartis' => '7880',
      'Siemens' => '7828',
      'Harley-Davidson' => '7739',
      'Gucci' => '7158',
      'eBay' => '6755',
      'Philips' => '6730',
      'Accenture' => '6728',
      'MTV' => '6627',
      'Nintendo' => '6559',
      'Gap' => '6416',
      "L'Oréal" => '6392',
      'Heinz' => '6223',
      'Yahoo!' => '6056',
      'Volkswagen' => '6032',
      'Xerox' => '5918',
      'Colgate' => '5633',
      'Wrigley' => '5449',
      'KFC' => '5350',
      'Chanel' => '5156',
      'Avon' => '5040',
      'Nestlé' => '4932',
      'Kleenex' => '4842',
      'Amazon' => '4707',
      'Pizza Hut' => '4694',
      'Danone' => '4638',
      'Caterpillar' => '4580',
      'Motorola' => '4569',
      'Kodak' => '4406',
      'adidas' => '4290',
      'Rolex' => '4237',
      'Zara' => '4235',
      'Audi' => '4165',
      'Hyundai' => '4078',
      'BP' => '4010',
      'Panasonic' => '3977',
      'Reuters' => '3961',
      'Kraft' => '3943',
      'Porsche' => '3927',
      'Hermès' => '3854',
      'Tiffany & Co.' => '3819',
      'Hennessy' => '3576',
      'Duracell' => '3576',
      'ING' => '3474',
      'Cartier' => '3360',
      'Moët & Chandon' => '3257',
      'Johnson & Johnson' => '3193',
      'Shell' => '3173',
      'Nissan' => '3108',
      'Starbucks' => '3099',
      'Lexus' => '3070',
      'Smirnoff' => '3032',
      'LG' => '3010',
      'Bulgari' => '2875',
      'Prada' => '2874',
      'Armani' => '2783',
      'Burberry' => '2783',
      'Nivea' => '2692',
      "Levi's" => '2689'
    }
  ],
  [
    2007-01-01T00:00:00.000Z,
    InternMap(100) [Map] {
      'Coca-Cola' => '65324',
      'Microsoft' => '58709',
      'IBM' => '57090',
      'GE' => '51569',
      'Nokia' => '33696',
      'Toyota' => '32070',
      'Intel' => '30954',
      "McDonald's" => '29398',
      'Disney' => '29210',
      'Mercedes-Benz' => '23568',
      'Citi' => '23442',
      'HP' => '22197',
      'BMW' => '21612',
      'Marlboro' => '21282',
      'American Express' => '20827',
      'Gillette' => '20415',
      'Louis Vuitton' => '20321',
      'Cisco' => '19099',
      'Honda' => '17998',
      'Google' => '17837',
      'Samsung' => '16853',
      'Merrill Lynch' => '14343',
      'HSBC' => '13563',
      'NESCAFÉ' => '12950',
      'Sony' => '12907',
      'Pepsi' => '12888',
      'Oracle' => '12448',
      'UPS' => '12013',
      'Nike' => '12003',
      'Budweiser' => '11652',
      'Dell' => '11554',
      'J.P. Morgan' => '11433',
      'Apple' => '11037',
      'SAP' => '10850',

In [21]:
function rank(value) {
    const data = Array.from(names, name => ({name, value: value(name)}));
    data.sort((a, b) => d3.descending(a.value, b.value));
    for (let i = 0; i < data.length; i++) data[i].rank = Math.min(n, i);
    return data;
}

In [24]:
rank(name => datevalues[0][1].get(name))

[
  { name: 'Xerox', value: '9699', rank: 0 },
  { name: 'Dell', value: '9476', rank: 1 },
  { name: 'Gap', value: '9316', rank: 2 },
  { name: 'Nike', value: '8015', rank: 3 },
  { name: 'Volkswagen', value: '7834', rank: 4 },
  { name: 'Ericsson', value: '7805', rank: 5 },
  { name: "Kellogg's", value: '7357', rank: 6 },
  { name: 'Coca-Cola', value: '72537', rank: 7 },
  { name: 'Microsoft', value: '70196', rank: 8 },
  { name: 'Louis Vuitton', value: '6887', rank: 9 },
  { name: 'Pepsi', value: '6636', rank: 10 },
  { name: 'Apple', value: '6594', rank: 11 },
  { name: 'MTV', value: '6411', rank: 12 },
  { name: 'Yahoo!', value: '6299', rank: 12 },
  { name: 'SAP', value: '6135', rank: 12 },
  { name: 'IKEA', value: '6031', rank: 12 },
  { name: 'Duracell', value: '5885', rank: 12 },
  { name: 'Philips', value: '5481', rank: 12 },
  { name: 'IBM', value: '53183', rank: 12 },
  { name: 'Samsung', value: '5223', rank: 12 },
  { name: 'Gucci', value: '5149', rank: 12 },
  { name: 'Kleenex', value: '5144', rank: 12 },
  { name: 'Reuters', value: '4876', rank: 12 },
  { name: 'AOL', value: '4531', rank: 12 },
  { name: 'Amazon', value: '4528', rank: 12 },
  { name: 'Motorola', value: '4445', rank: 12 },
  { name: 'Colgate', value: '4417', rank: 12 },
  { name: 'Wrigley', value: '4324', rank: 12 },
  { name: 'Chanel', value: '4141', rank: 12 },
  { name: 'Intel', value: '39048', rank: 12 },
  { name: 'Nokia', value: '38528', rank: 12 },
  { name: 'GE', value: '38127', rank: 12 },
  { name: 'adidas', value: '3791', rank: 12 },
  { name: 'Panasonic', value: '3734', rank: 12 },
  { name: 'Ford', value: '36368', rank: 12 },
  { name: 'Rolex', value: '3561', rank: 12 },
  { name: 'Hertz', value: '3438', rank: 12 },
  { name: 'Disney', value: '33553', rank: 12 },
  { name: 'Bacardi', value: '3187', rank: 12 },
  { name: 'BP', value: '3066', rank: 12 },
  { name: 'Moët & Chandon', value: '2799', rank: 12 },
  { name: 'Shell', value: '2786', rank: 12 },
  { name: "McDonald's", value: '27859', rank: 12 },
  { name: 'Burger King', value: '2701', rank: 12 },
  { name: 'AT&T', value: '25548', rank: 12 },
  { name: 'Smirnoff', value: '2443', rank: 12 },
  { name: 'Barbie', value: '2315', rank: 12 },
  { name: 'Heineken', value: '2218', rank: 12 },
  { name: 'Marlboro', value: '22110', rank: 12 },
  { name: 'Wall Street Journal', value: '2184', rank: 12 },
  { name: 'Mercedes-Benz', value: '21104', rank: 12 },
  { name: 'HP', value: '20572', rank: 12 },
  { name: 'Cisco', value: '20067', rank: 12 },
  { name: 'Toyota', value: '18823', rank: 12 },
  { name: 'Citi', value: '18809', rank: 12 },
  { name: 'Ralph Lauren', value: '1834', rank: 12 },
  { name: 'Gillette', value: '17358', rank: 12 },
  { name: 'Sony', value: '16409', rank: 12 },
  { name: 'American Express', value: '16122', rank: 12 },
  { name: 'Johnnie Walker', value: '1541', rank: 12 },
  { name: 'Honda', value: '15244', rank: 12 },
  { name: 'Hilton', value: '1483', rank: 12 },
  { name: "Jack Daniel's", value: '1480', rank: 12 },
  { name: 'Compaq', value: '14602', rank: 12 },
  { name: 'Armani', value: '1456', rank: 12 },
  { name: 'Pampers', value: '1400', rank: 12 },
  { name: 'NESCAFÉ', value: '13680', rank: 12 },
  { name: 'Starbucks', value: '1329', rank: 12 },
  { name: 'BMW', value: '12969', rank: 12 },
  { name: 'Guinness', value: '1224', rank: 12 },
  { name: 'Kodak', value: '11822', rank: 12 },
  { name: 'Heinz', value: '11742', rank: 12 },
  { name: 'Financial Times', value: '1148', rank: 12 },
  { name: 'Budweiser', value: '10684', rank: 12 },
  { name: 'Benetton', value: '1008', rank: 12 },
  { name: 'Merrill Lynch', value: undefined, rank: 12 },
  { name: 'Oracle', value: undefined, rank: 12 },
  { name: 'Merck & Co., Inc.', value: undefined, rank: 12 },
  { name: 'Nintendo', value: undefined, rank: 12 },
  { name: 'Pfizer', value: undefined, rank: 12 },
  { name: 'Goldman Sachs', value: undefined, rank: 12 },
  { name: 'Canon', value: undefined, rank: 12 },
  { name: 'Pizza Hut', value: undefined, rank: 12 },
  { name: 'Harley-Davidson', value: undefined, rank: 12 },
  { name: 'KFC', value: undefined, rank: 12 },
  { name: 'Sun Microsystems', value: undefined, rank: 12 },
  { name: 'Avon', value: undefined, rank: 12 },
  { name: 'Boeing', value: undefined, rank: 12 },
  { name: 'Texas Instruments', value: undefined, rank: 12 },
  { name: 'Kraft', value: undefined, rank: 12 },
  { name: "Levi's", value: undefined, rank: 12 },
  { name: 'Time', value: undefined, rank: 12 },
  { name: 'Tiffany & Co.', value: undefined, rank: 12 },
  { name: 'Mobil', value: undefined, rank: 12 },
  { name: 'FedEx', value: undefined, rank: 12 },
  { name: 'Nivea', value: undefined, rank: 12 },
  { name: 'Absolut', value: undefined, rank: 12 },
  { name: 'Carlsberg', value: undefined, rank: 12 },
  { name: 'Siemens', value: undefined, rank: 12 },
  { name: 'Swatch', value: undefined, rank: 12 },
  ... 73 more items
]

In [25]:
k = 10

10

In [37]:
keyframes = {
    const keyframes = [];
    let ka, a, kb, b;
    for ([[ka, a], [kb, b]] of d3.pairs(datevalues)) {
        for (let i = 0; i < k; i++) {
            const t = i / k;
            keyframes.push([
            new Date(ka * (1 - t) + kb * t),
            rank(name => (a.get(name) || 0) * (1 - t) + (b.get(name) || 0) * t)
            ]);
        }
    }
    keyframes.push([new Date(kb), rank(name => b.get(name) || 0)]);
    return keyframes;
}

SyntaxError: Unexpected identifier 'keyframes'